version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /vcf_merge.wdl
     testParameterFiles:
         - /tests/gs.json
         - /tests/drs.json
     authors:
      - name: Brian Hannafious
      - name: Lon Blauvelt
        email: lblauvel at ucsc dot edu
        affiliation: UC Santa Cruz
     name: xvcfmerge
